camunda.bpm:
  webapp:
    index-redirect-enabled: true
  admin-user:
    id: admin
    password: admin

endpoint:
  rezscore: https://rezscore.com/a/112084
  mail: https://maker.ifttt.com/trigger/send_mail/with/key/m-fpW1lKoHE5kzbhe5IPUIkuD5J4L6OeNYzrHzpCXPK

logging.level:
  ch.fhnw: DEBUG